apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analyse-chess-game
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '25'
    spec:
      timeoutSeconds: 900
      containers:
      - image:
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi