
name: Deploy Cloud Function

env:
  PROJECT: united-axle-390115

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: Set-Up
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501,W503
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Pytest
      run: python -m pytest

  Deploy:
    needs: Validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: 'actions/checkout@v3'

    - id: Authenticate-GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: Deploy-Cloud-Run
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
  